version: '3'

services:
  gameframe-gateway:
    build: .
    container_name: gameframe-gateway
    expose:
      - "8000/tcp"
    networks:
      - gameframe-internal-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - INTERNAL_APP_NAME=${INTERNAL_APP_NAME}
      - SERVICE_INTERNAL_PORT=${SERVICE_INTERNAL_PORT}
      - EUREKA_URI=${EUREKA_URI}

networks:
  gameframe-internal-network:
    external: true
