version: '3'

services:
  gameframe-gateway:
    build: .
    container_name: gameframe-gateway
    expose:
     - "8000/tcp"
    networks:
      default:
      gameframe-internal-network:
        ipv4_address: 172.18.0.100
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

networks:
  gameframe-internal-network:
    external: true

