version: '3'

services:
  gameframe-gateway:
    build: .
    container_name: gameframe-gateway
    ports:
      - "8000:8000"
    expose:
      - "8000/tcp"
    networks:
      - gameframe-internal-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  gameframe-internal-network:
    external: true
